
export const dummyCars = [
  {
    id: 1,
    name: 'トヨタ ヤリス',
    grade: 'G',
    capacity: 5,
    price: 8000,
    image: '/images/yaris.png',
    features: ['ナビ', 'ETC', '禁煙'],
    make: 'トヨタ',
    model: 'ヤリス',
    type: 'コンパクト',
    store: '東京駅前店',
  },
  {
    id: 2,
    name: 'ホンダ フィット',
    grade: 'e:HEV HOME',
    capacity: 5,
    price: 8500,
    image: '/images/fit.png',
    features: ['ナビ', 'ETC', '喫煙可'],
    make: 'ホンダ',
    model: 'フィット',
    type: 'コンパクト',
    store: '新宿西口店',
  },
  {
    id: 3,
    name: '日産 ノート',
    grade: 'e-POWER X',
    capacity: 5,
    price: 9000,
    image: '/images/note.png',
    features: ['ナビ', 'ETC', '禁煙'],
    make: '日産',
    model: 'ノート',
    type: 'コンパクト',
    store: '品川駅港南口店',
  },
  {
    id: 4,
    name: 'トヨタ アルファード',
    grade: 'S Cパッケージ',
    capacity: 7,
    price: 15000,
    image: '/images/alphard.png',
    features: ['ナビ', 'ETC', '禁煙', '後席モニター'],
    make: 'トヨタ',
    model: 'アルファード',
    type: 'ミニバン',
    store: '渋谷道玄坂店',
  },
];

export const dummyOptions = [
  {
    id: 'opt1',
    name: 'チャイルドシート',
    price: 1000,
  },
  {
    id: 'opt2',
    name: 'ジュニアシート',
    price: 1000,
  },
  {
    id: 'opt3',
    name: 'スタッドレスタイヤ',
    price: 4000,
  },
  {
    id: 'opt4',
    name: 'ペット同乗',
    price: 2000,
  },
];
